name: fpl_mobile
description: FPL Alpha - Flutter Mobile Companion App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  dio: ^5.4.1
  go_router: ^14.2.0
  json_annotation: ^4.9.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.5
  webview_flutter: ^4.10.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter:
  uses-material-design: true
